[workspace]
members = ["crates/nezha-types", "crates/nezha-core", "crates/nezha-compositor", "crates/nezha-renderer", "crates/nezha-egui", "crates/nezha-archive", "crates/nezha-dms", "crates/nezha-encoder", "crates/nezha-text", "crates/nezha-xsynth", "crates/nezha-media"]
resolver = "2"

[workspace.dependencies]
wgpu = "29.0.3"
eframe = { version = "0.34.2", features = ["wgpu"] }
egui = "0.34.2"
pollster = "0.4"
bytemuck = { version = "1", features = ["derive"] }
puffin = "0.20"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2.0.18"
midly = "0.5.3"
hound = "3.5.1"
image = "0.25"
flate2 = "1.1.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rust-i18n = "3.0"
sys-locale = "0.3"

[profile.fast-release]
inherits = "release"                # 基于 release 默认设置
opt-level = 1                       # 基本优化，编译速度远快于 3
lto = false                         # 禁用链接时优化（大幅减少链接时间）
codegen-units = 16                  # 增加并行代码生成单元（最大 16，加速编译）
debug = 1                           # 行号表（函数名+行号），支持 backtrace 和 profiler
strip = "none"                      # 保留符号用于调试分析（体积换调试能力）
panic = "abort"                    # 使用 abort 而非 unwind（减少生成的代码量）
incremental = true                 # 启用增量编译（对多次构建友好）

